cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('add/package/<int:item_id>/', views.add_package_to_cart, name='add_package_to_cart'),
    path('remove-from-cart/<str:item_type>/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('edit/<int:service_id>/', views.edit_cart_item, name='edit_cart_item'),
    path('<int:service_id>/get_available_times/', views.get_available_times, name='get_available_times'),
    path('<int:service_id>/get_booked_times/', views.get_booked_times, name='get_booked_times'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>/', views.order_history, name='order_history'),
]

saba_salon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('services/', include('services.urls')),
    path('cart/', include('cart.urls')),
    path('packages/', include('packages.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('reviews/', include('reviews.urls')),
    path('contact/', include('contact.urls')),
    path('team/', include('team.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.all_services, name='all_services'),
    path('<int:service_id>/', views.service_detail, name='service_detail'),
    path('<int:service_id>/get_available_times/', views.get_available_times, name='get_available_times'),
    path('<int:service_id>/get_booked_times/', views.get_booked_times, name='get_booked_times'),
    path('add/', views.add_service, name='add_service'),
    path('edit/<int:service_id>/', views.edit_service, name='edit_service'),
    path('delete/<int:service_id>/', views.delete_service, name='delete_service'),
    path('generate_time_slots/', views.generate_time_slots, name='generate_time_slots'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.team_list, name='team_list'),
    path('add/', views.add_staff_member, name='add_staff_member'),
    path('staff/<int:pk>/edit/', views.edit_staff_member, name='edit_staff_member'),
    path('staff/<int:pk>/delete/', views.delete_staff_member, name='delete_staff_member'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    {% block meta %}
    <!-- Basic metadata for compatibility and character encoding -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Saba Salon offers premium beauty and wellness services including haircuts, styling, facials, and makeup. Experience top-notch care from our expert team in a relaxing environment. Book your appointment today!">
    {% endblock %}

    {% block extra_meta %}
    <!-- Additional meta tags can be added here -->
    {% endblock %}

    {% block corecss %}
    <!-- Core CSS libraries and stylesheets -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&display=swap">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    {% endblock %}

    {% block extra_css %}
    <!-- Additional CSS files can be included here -->
    {% endblock %}

    {% block corejs %}
    <!-- Core JavaScript libraries -->
    <script src="https://kit.fontawesome.com/45b8f34d90.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    {% endblock %}

    {% block extra_js %}
    <!-- Additional JavaScript files can be included here -->
    {% endblock %}

    <title>Saba Salon {% block extra_title %}{% endblock %}</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <header class="container-fluid fixed-top">
        <div id="topnav" class="row bg-white pt-lg-2 d-none d-lg-flex">
            <!-- Logo and Search Form -->
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0 text-center text-lg-left">
                <a href="{% url 'home' %}" class="nav-link main-logo-link">
                    <img src="{% static 'images/logo.png' %}" alt="Saba Salon Logo" class="logo-img">
                </a>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <!-- Search form for services -->
                <form method="GET" action="{% url 'services:all_services' %}">
                    <div class="input-group w-100">
                        <input class="form-control border border-black" type="text" name="q"
                            placeholder="Search our services">
                        <div class="input-group-append">
                            <button class="form-control btn btn-black border border-black" type="submit">
                                <span class="icon">
                                    <i class="fas fa-search"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <!-- User options and cart summary -->
                <ul class="list-inline list-unstyled text-center text-lg-right my-0">
                    <li class="list-inline-item dropdown">
                        <a class="text-black nav-link" href="#" id="user-options" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <div class="text-center">
                                <div><i class="fas fa-user fa-lg"></i></div>
                                <p class="my-0">My Account</p>
                            </div>
                        </a>
                        <div class="dropdown-menu border-0" aria-labelledby="user-options">
                            {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser %}
                                    <a href="{% url 'services:add_service' %}" class="dropdown-item">Service Management</a>
                                    <a href="{% url 'packages:add_package' %}" class="dropdown-item">Package Management</a>
                                    <a href="{% url 'team:add_staff_member' %}" class="dropdown-item">Staff Management</a>
                                {% endif %}
                                <a href="{% url 'profiles:profile' %}" class="dropdown-item">My Profile</a>
                                <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
                            {% else %}
                                <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
                                <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="list-inline-item">
                        <!-- Cart summary link with dynamic total amount -->
                        <a class="{% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link total"
                            href="{% url 'cart:view_cart' %}">
                            <div class="text-center">
                                <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                                <p class="my-0">
                                    {% if grand_total %}
                                    ${{ grand_total|floatformat:2 }}
                                    {% else %}
                                    $0.00
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0"></div>
        </div>
        <!-- Main navigation -->
        <div class="row bg-white">
            <nav class="navbar navbar-expand-lg navbar-light w-100">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav"
                    aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% include 'includes/mobile-top-header.html' %}
                {% include 'includes/main-nav.html' %}
            </nav>
        </div>
    </header>

    <main class="flex-grow-1">
        {% block page_header %}
        <!-- Display flash messages if present -->
        {% if messages %}
        <div class="message-container mt-4">
            {% for message in messages %}
            {% with message.level as level %}
                {% if level == 40 %}
                {% include 'includes/toasts/toast_error.html' %}
                {% elif level == 30 %}
                {% include 'includes/toasts/toast_warning.html' %}
                {% elif level == 25 %}
                {% include 'includes/toasts/toast_success.html' %}
                {% else %}
                {% include 'includes/toasts/toast_info.html' %}
                {% endif %}
            {% endwith %}
            {% endfor %}
        </div>
        {% endif %}
        {% endblock %}

        {% block content %}
        <!-- Main content of the page will be rendered here -->
        {% endblock %}
    </main>

    {% block postloadjs %}
    <!-- JavaScript to initialize any post-load functionality, such as showing toast notifications -->
    <script>
        $('.toast').toast('show');
    </script>
    {% endblock %}

    <footer class="bg-light text-dark py-4 mt-auto">
        <div class="container">
            <!-- Social media links -->
            <section class="mb-4 d-flex flex-column flex-md-row align-items-center justify-content-center">
                <h6 class="h4 mb-3 mb-md-0 mr-md-4">Follow Us</h6> 
                <div class="social-icons d-flex flex-wrap justify-content-center">
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://www.facebook.com/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://twitter.com/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://plus.google.com/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-google"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://www.instagram.com/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://www.linkedin.com/in/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="https://github.com/yourprofile"
                        role="button" target="_blank">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </section>
    
            <!-- Footer text -->
            <div class="text-center text-dark">
                <p class="mb-0">&copy; 2024 Saba Salon. All rights reserved.</p>
            </div>
        </div>
    </footer>
    
</body>

</html>